--- Revenue Analysis
--- Project : Product Growth Intelligence Copilot

--- Business Question: What is the total revenue generated by the company?
--- What is the AOV (Average Order Value) for the orders?
--- What is the revenue trend over time (monthly/quarterly/yearly)?
--- Which states generate the most revenue?


select count(*) from order_items;